package com.tencent.angel.ml.matrix;

public enum MatrixOpLogType {
  DENSE_DOUBLE,
  SPARSE_DOUBLE,
  DENSE_INT,
  SPARSE_INT,
  DENSE_FLOAT,
  SPARSE_FLOAT,
  SPARSE_DOUBLE_LONGKEY,
  COMPONENT_SPARSE_DOUBLE_LONGKEY,
  COMPONENT_SPARSE_DOUBLE,
  COMPONENT_SPARSE_FLOAT,
  COMPONENT_SPARSE_INT
}
